NumPy is a python library used to work with numerical data efficiently

numpy array : faster.more powerful list

numpy is used to perform fast mathematical operations on large datasets using arrays

- it is faster
- easy to calculate
- better for large datasets
- more powerful than normal python lists
 we can store data in arrays and perform operations like :
 - mean
 - max
 - sum
 - calculations


In [7]:
import numpy as np
numbers=np.array([10,20,30,40])
print(numbers)

[10 20 30 40]


In [8]:
"find the average"
print(numbers.mean())

25.0


In [10]:
"find max and min"
print(numbers.max())
print(numbers.min())

40
10


In [11]:
import numpy as np
marks=np.array([75,82,90,68,88])
print("average:",marks.mean())
print("highest:",marks.max())

average: 80.6
highest: 90


ARRAY DIMENSIONS

dimension=no of directions data is arranged

1d : a line

2d : a table

3d : multiple tables stacked

we use dimensions when working with 
- excel tables
- customer data
- sales reports

1-D array : this is like a normal list (one row)

In [13]:
import numpy as np
arr1=np.array([10,20,30,40])
print(arr1)
print(arr1.ndim)

[10 20 30 40]
1


2-D array : this is like a table (rows and columns)



In [14]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


3-D array : this is like multiple tables stacked together

In [15]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3)
print(arr3.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


NOTE :

arr.ndim  # no of dim

arr.shape # rows & columns

arr.size # no of elements

In [18]:
import numpy as np
data=np.array([
    [1,2],
    [3,4],
    [5,6]
    ])
print("dim:",data.ndim)
print("shape:",data.shape)


dim: 2
shape: (3, 2)


PRACTICE 

In [19]:
# 1. find the dimension
import numpy as np
arr=np.array([10,20,30])
print(arr.ndim)

1


In [20]:
# 2. identify dimension type
import numpy as np
arr=np.array([[1,2],
              [3,4]
              ])
print(arr.ndim)
print(arr.shape)

2
(2, 2)


In [21]:
# 3. create a 3d array & find no of dimensions and reshape
arr=np.array([[[1,2],
               [3,4]],
              [ [5,6],
               [7,8]]])
print(arr.ndim)
print(arr.shape)


3
(2, 2, 2)


In [22]:
# 4. check total elements
arr=np.array([[5,10,15],
              [20,25,30]])
print(arr.ndim)
print(arr.shape)
print(arr.size)

2
(2, 3)
6
