SORTING IN NUMPY

SORT A 1D ARRAY


In [1]:
import numpy as np
arr=np.array([5,2,9,1])
sorted_arr=np.sort(arr)
print(sorted_arr)

[1 2 5 9]


SORT ROWS (axis=1)

In [2]:
arr=np.array([[3,1,2],
              [9,7,8]])
sorted_arr=np.sort(arr,axis=1)
print(sorted_arr)

[[1 2 3]
 [7 8 9]]


SORT COLUMNS (axis=0)

In [3]:
arr=np.array([[3,1],
              [2,4]])
sorted_arr=np.sort(arr,axis=0)
print(sorted_arr)

[[2 1]
 [3 4]]


FILTERING IN NUMPY

- filtering : select elements based on condition

- used in data cleaning , data analysis , machine learning

In [4]:
# filter nums greater than 10
arr=np.array([5,12,7,20])
result=arr[arr>10]
print(result)

[12 20]


In [5]:
# filter even nums
arr=np.array([1,2,3,4,5,6])
result=arr[arr%2==0]
print(result)

[2 4 6]


PRACTICE

In [6]:
#1 sort a 1d array
arr=np.array([8,3,6,1])
sorted_arr=np.sort(arr)
print(sorted_arr)

[1 3 6 8]


In [7]:
#2 sort rows
arr=np.array([[4,2,3],
              [9,1,7]])
result=np.sort(arr,axis=1)
print(result)

[[2 3 4]
 [1 7 9]]


In [8]:
#3 sort columns
arr=np.array([[5,2],
              [1,4]])
result=np.sort(arr,axis=0)
print(result)

[[1 2]
 [5 4]]


In [11]:
#4 filter nums greater than 15
arr=np.array([10,20,5,30])
result=arr[arr>15]
#result=arr>15     # [False  True False  True] returns boolean
print(result)

[20 30]


In [19]:
#5 filter even numbers
arr=np.array([3,6,9,12,15])
res=arr[arr%2==0]
print(res)

[ 6 12]


In [14]:
#6 filter nums less than 50 
arr=np.array([25,60,45,80])
res=arr[arr<50]
print(res)

[25 45]


In [18]:
#7 sort then filter
arr=np.array([40,10,30,20])
new_arr=np.sort(arr)
res=new_arr[new_arr>20]
print(new_arr)
print(res)

[10 20 30 40]
[30 40]


AGGREGATION FUNCTIONS IN NUMPY

- aggregation : calculating a single value from many values

EXAMPLES

- sum : total
- mean : average
- max : largest
- min : smallest

In [20]:
# SUM - total of elements
import numpy as np
arr=np.array([10,20,30])
print(np.sum(arr))

60


In [21]:
# SUM WITH AXIS 
arr=np.array([[1,2],
              [3,4]])
print(np.sum(arr,axis=1))

[3 7]


In [22]:
print(np.sum(arr,axis=0))

[4 6]


In [23]:
# MEAN - average
arr=np.array([10,20,30])
print(np.mean(arr))

20.0


In [24]:
# MAX - largest value
arr=np.array([5,12,7])
print(np.max(arr))

12


In [25]:
# MIN - smallest value
arr=np.array([5,12,7])
print(np.min(arr))

5


In [26]:
# ARGMAX - index of largest value
arr=np.array([5,12,7])
print(np.argmax(arr))

1


In [27]:
# ARGMIN - index of smallest value
arr=np.array([5,12,7])
print(np.argmin(arr))

0


PRACTICE

In [28]:
#1 find sum
arr=np.array([5,10,15])
print(np.sum(arr))

30


In [29]:
#2 find mean
arr=np.array([2,4,6,8])
print(np.mean(arr))

5.0


In [30]:
#3 find max value
arr=np.array([12,7,25,3])
print(np.max(arr))

25


In [31]:
#4 find min value
arr=np.array([9,2,14])
print(np.min(arr))

2


In [35]:
#5 find index of largest value
arr=np.array([10,30,20])
print(np.argmax(arr))

1


In [33]:
#6 sum of col
arr=np.array([[1,2],
              [3,4]])
print(np.sum(arr,axis=0))

[4 6]


In [34]:
#7 sum of rows
arr=np.array([[1,2],
              [3,4]])
print(np.sum(arr,axis=1))

[3 7]
