NUMPY RESHAPING ( changing structure )

reshaping=changing the shape of the array without changing the data
- same numbers,different layout

RULE : total elements must remain the same

In [ ]:
# reshape 1D to 2D
import numpy as np
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)    # 2=rows,3=columns
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
data=np.array([10,20,30,40,50,60])
reshaped=data.reshape(3,2)     # 3=rows,2=columns
print(reshaped)
print("element:",reshaped[1,0])   # 1=row(index) , 0=col(index)

[[10 20]
 [30 40]
 [50 60]]
element: 30


PRACTICE 


In [4]:
# 1. reshape 1d to 2d 
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [5]:
# 2. reshape 2d to 3*2
arr=np.array([[10,20,30],
              [40,50,60]])
new_arr=arr.reshape(3,2)
print(new_arr)

[[10 20]
 [30 40]
 [50 60]]


In [ ]:
# check if reshape is possible for (4,2)
arr=np.array([1,2,3,4,5,6])
new_arr=arr.reshape(4,2)
print(new_arr)     # NO ,BECOZ THE NO OF ELEMENTS MUST SAME

ValueError: cannot reshape array of size 6 into shape (4,2)

In [14]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr.ndim)
new_arr=arr.reshape(3,2)
print(new_arr)
print(new_arr[2,1])

1
[[10 20]
 [30 40]
 [50 60]]
60
