ARRAY SLICING AND VIEW VS COPY

- this topic is used in real data analysis when you want to select part of data or avoid changing the original dataset  

ARRAY SLICING ( selecting multiple values)

- slicing = selecting a range of elements from an array
- syntax :arr[start:end]
- rule : start index is included , end index is excluded

In [1]:
# 1d array slicing
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:4])

[20 30 40]


In [2]:
# 2d array slicing ( arr[row_start:row_end,col_strt:col_end])
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(arr[0:2,1:3])



[[2 3]
 [5 6]]


PRACTICE 


In [3]:
import numpy as np
arr=np.array([5,10,15,20,25])
print(arr[2:5])

[15 20 25]


In [4]:
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
print(arr[1: ,1: ])

[[50 60]
 [80 90]]


In [1]:
# simple slice
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[1:3])

[20 30]


In [15]:
# print last 3 elements
import numpy as np
arr=np.array([5,10,15,20,25,30])
print(arr[-3:])

[20 25 30]


In [17]:
# skip elements
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[1:8:2])

[2 4 6 8]


In [20]:
# reverse an array
arr=np.array([10,20,30,40])
print(arr[::-1])

[40 30 20 10]


In [22]:
# 2d array slicing 
# print first row
import numpy as np
arr=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(arr[0:1])


[[1 2 3]]


In [30]:
# print first column
print(arr[:,0])

[1 4 7]


In [31]:
# print submatrix
print(arr[1:3,1:3])

[[5 6]
 [8 9]]


In [32]:
# extract middle values
import numpy as np
data=np.array([100,200,300,400,500])
print(data[1:4])

[200 300 400]


In [33]:
# modify a slice
import numpy as np
arr=np.array([1,2,3,4,5])
slice_arr=arr[1:4]
slice_arr[:]=0
print(arr)

[1 0 0 0 5]


In [37]:
# dataset selection
import numpy as np
sales=np.array([[100,200,300],
                [400,500,600],
                [700,800,900]])
print(sales[0:2])
print(sales[:,-1])
print(sales[1:,1:])

[[100 200 300]
 [400 500 600]]
[300 600 900]
[[500 600]
 [800 900]]


In [7]:
# mini real world challenge
import numpy as np
data=np.array([[101,5000,25],
               [102,6000,30],
               [103,5500,28],
               [104,7000,35]])
# columns are employee id|salary|age

# task 1 : print only salaries
print(data[:,[1]])

# task 2 : print last two rows
print(data[2:,:])

# task 3 : reverse the rows
print(data[::-1,:])

# task 4 : extract the submatrix
print(data[1:3,1:])

# task 5 : view vs copy check
subset=data[1:3]
subset[0,0]=999
print(data)

[[5000]
 [6000]
 [5500]
 [7000]]
[[ 103 5500   28]
 [ 104 7000   35]]
[[ 104 7000   35]
 [ 103 5500   28]
 [ 102 6000   30]
 [ 101 5000   25]]
[[6000   30]
 [5500   28]]
[[ 101 5000   25]
 [ 999 6000   30]
 [ 103 5500   28]
 [ 104 7000   35]]
