WHAT IS A VIEW ?

view = reference to original data

if uh change the view,the original array also changes bcoz view shares the original array

In [ ]:
import numpy as np
arr=np.array([10,20,30,40])
view_arr=arr[1:3]
view_arr[0]=99
print(view_arr)  
print(arr)    # changes in original also

[99 30]
[10 99 30 40]


WHAT IS COPY ?

- copy = completely separate data

- copy has its own memory

- if you change the copy , the original array does not change

In [ ]:
import numpy as np
arr=np.array([10,20,30,40])
copy_arr=arr[1:3].copy()
copy_arr[0]=99
print(arr)
print(copy_arr)    # changes only in copy

[10 20 30 40]
[99 30]


PRACTICE


In [ ]:
# basic slicing
import numpy as np
arr=np.array([1,2,3,4])
new_arr=arr[1:3]
new_arr[0]=100
print(arr)       # original changes

[  1 100   3   4]


In [ ]:
arr=np.array([10,20,30])
new_arr=arr.copy()
new_arr[0]=99
print(arr)      # does not affect original

[10 20 30]


In [ ]:
# identify view       , it is a view
import numpy as np
arr=np.array([10,20,30,40])
new_arr=arr[1:3]
new_arr[0]=99
print(arr)     

[10 99 30 40]


In [ ]:
# modify and prevent original change
import numpy as np
arr=np.array([10,20,30,40])
new_arr=arr.copy()
new_arr[0]=5
print(arr)

[10 20 30 40]


In [12]:
# check base attribute
import numpy as np
arr=np.array([10,20,30,40])
new_arr=arr[1:4]
new_arr[2]=25
print(arr.base)

None
