MAJOR OPERATIONS - row wise operations

Major Operations = operations across rows

- axis = 1 [row operation]

In [8]:
import numpy as np
data=np.array([[5,6],
               [8,9]])
np.sum(data,axis=1)

array([11, 17])

MINOR OPERATIONS - column wise operations

Minor Operations = operations across columns

- axis=0 [column operation]

In [9]:
np.sum(data,axis=0)

array([13, 15])

COMMON MAJOR AND MINOR OPERATIONS 

- SUM

np.sum(data,axis=0) # column(minor)

np.sum(data,axis=1) # row(major)

- MEAN 

np.mean(data,axis=0) 

np.mean(data,axis=1)

- MAXIMUM

np.max(data,axis=0)

np.max(data,axis=1)

- MINIMUM

np.min(data,axis=0)

np.min(data,axis=1)

- COUNT

np.count_nonzero(data,axis=0)






PRACTICE

In [10]:
import numpy as np
data=np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
# column sum
np.sum(data,axis=0)

array([120, 150, 180])

In [11]:
# row sum
np.sum(data,axis=1)

array([ 60, 150, 240])

In [12]:
# column mean
np.mean(data,axis=0)

array([40., 50., 60.])

In [13]:
# max value in rows
np.max(data,axis=1)

array([30, 60, 90])

In [14]:
import numpy as np
data=np.array([[101,5000,25],
               [102,6000,30],
               [103,5500,28],
               [104,7000,35]])
# columns : id|salary|age

In [15]:
#1 find sum of each col
np.sum(data,axis=0)

array([  410, 23500,   118])

In [16]:
# 2 find sum of each row
np.sum(data,axis=1)

array([5126, 6132, 5631, 7139])

In [18]:
# 3 find the avg salary
np.mean(data[:,1],axis=0)

np.float64(5875.0)

In [19]:
# 4 find max age
np.max(data[:,2],axis=0)

np.int64(35)

In [40]:
# 5 count employees
(data.shape[0])

4

In [41]:
# 6 find max salary
np.min(data[:,1],axis=0)

np.int64(5000)

In [32]:
# 7 find mean of age
np.mean(data[:,2],axis=0)

np.float64(29.5)

In [ ]:
# 8 find the row with highest salary     [ to find row use arg]
np.argmax(data[:,1],axis=0)

np.int64(3)

In [34]:
# 9 find the total salary of all employee
np.sum(data[:,1],axis=0)

np.int64(23500)

In [35]:
# 10 find column wise max values
np.max(data,axis=0)

array([ 104, 7000,   35])