APPEND - add new row or column

- row : axis=0

- col : axis=1

- syntax : np.append(data,[rows],axis=0)

- syntax : np.append(data,[col],axis=1)

INSERT - add at a specific position

- syntax : np.insert(data,index,[row],axis=0)

DELETE - remove row or column

- syntax : np.delete(data, index,axis=0/1)





PRACTICE 


In [17]:
# 1 append a row
import numpy as np
arr=np.array([
    [10,20],
    [30,40]
])
np.append(arr,[[50,60]],axis=0)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [18]:
# 2 append a column
np.append(arr,[[70],[80]],axis=1)

array([[10, 20, 70],
       [30, 40, 80]])

In [33]:
# 3 delete a row
arr=np.array([[1,2],
              [3,4],
              [5,6]])
np.delete(arr,1,axis=0)

array([[1, 2],
       [5, 6]])

In [34]:
# 4 delete a column 
arr=np.array([[9,8,7],
              [6,5,4]])
np.delete(arr,0,axis=1)

array([[8, 7],
       [5, 4]])

In [21]:
# 5 insert a row at position 1
arr=np.array([[100,200],
              [300,400]])
np.insert(arr,1,[[150,250]],axis=0)

array([[100, 200],
       [150, 250],
       [300, 400]])

In [22]:
# 6 insert a column at position 0
arr=np.array([[5,6],
              [7,8]])
np.insert(arr,0,[[1,2]],axis=1)

array([[1, 5, 6],
       [2, 7, 8]])

In [23]:
# 7 append multiple rows
arr=np.array([[2,4],
              [6,8]])
np.append(arr,[[10,12],[14,16]],axis=0)

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [24]:
# 8 delete last row
arr=np.array([[11,22],
              [33,44],
              [55,66]])
np.delete(arr,2,axis=0)

array([[11, 22],
       [33, 44]])

In [25]:
# 9 insert column in the middle
arr=np.array([[1,3],
              [5,7]])
np.insert(arr,1,[[2,6]],axis=1)

array([[1, 2, 3],
       [5, 6, 7]])

In [38]:
# 10 replace a column using delete + insert
arr=np.array([[10,20,30],
              [40,50,60]])
arr=np.delete(arr,1,axis=1)
new_col=np.array([[99],[88]])
arr=np.insert(arr,1,new_col,axis=1)
print(arr)


[[10 99 88 30]
 [40 99 88 60]]


In [39]:
# 11 append then delete 
arr=np.array([[1,2],
              [3,4]])
arr=np.append(arr,[[5,6]],axis=0)
arr=np.delete(arr,0,axis=0)
print(arr)

[[3 4]
 [5 6]]


In [40]:
# 12 find shape after operation
arr=np.array([[10,20,30],
              [40,50,60]])
arr=np.delete(arr,2,axis=1)
arr.shape

(2, 2)